ALTER TABLE config_data ADD COLUMN auto_export_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE config_data ADD COLUMN export_lrc BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE config_data ADD COLUMN export_txt BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE config_data ADD COLUMN export_embedded BOOLEAN NOT NULL DEFAULT FALSE;
